Repository wecode-bootcamp-korea/38-2nd-airB-frontend, pull requests merged in 2022-11, with the labels that each got.

#5 [38기 강은지]Hotfix: gitignore 수정
  .gitignore
Labels: 완료

#1 [38기 강은지] ADD: Footer 컴포넌트 생성
  jsonconfig.json
  src/components/BottomSheet/BottomSheet.js
  src/components/Footer/Footer.js
  src/pages/Main/Main.js
  src/styles/theme.js
Labels: 완료

#3 [38기 강은지]ADD: 카카오 로그인 추가
  src/Router.js
  src/components/SignIn/SignIn.js
  src/pages/KakaoLogin/KakaoLogin.js
  src/pages/Main/Main.js
  src/pages/SignIn/SignIn.js
Labels: 완료

#2 [38기 김우진]ADD: Filter 레이아웃 구현
  package-lock.json
  package.json
  src/Router.js
  src/pages/Filter/Filter.js
  src/pages/Filter/LocalFilter.js
  src/pages/Filter/ThemeFilter.js
  src/pages/Main/List/ListCard.js
Labels: 멘토 리뷰 요청

#4 [38기 정관훈]ADD: Host 레이아웃/기능
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/pages/Filter/Filter.js
  src/pages/Filter/LocalFilter.js
  src/pages/Filter/ThemeFilter.js
  src/pages/Host/DragDrop/Dropzone.js
  src/pages/Host/Host.js
  src/pages/Host/HostMessage/HostLanding.jsx
  src/pages/Host/HostResult.js
  src/pages/Host/HostStair/HostBed.js
  src/pages/Host/HostStair/HostHouse.js
  src/pages/Host/HostStair/HostInfo.js
  src/pages/Host/HostStair/HostMain.js
  src/pages/Host/HostStair/HostMap.js
  src/pages/Host/HostStair/HostPicture.js
  src/pages/Host/HostStair/HostPrice.js
  src/pages/Host/HostStair/HostView.js
  src/pages/Host/User.js
  src/pages/Main/List/ListCard.js
Labels: 완료

#9 [38기 강은지] ADD: common modal component added
  public/index.html
  src/components/Modal/Modal.js
  src/components/Modal/SignInModal.js
  src/components/SignIn/SignIn.js
  src/styles/theme.js
Labels: 수정 요청, 완료

#13 [38기 강은지] HOTFIX: routing 재설정
  src/Router.js
  src/pages/Main/Main.js
  src/pages/Main/MainLayout.js
Labels: 완료

#14 [38기 강은지] HOTFIX: config.js 파일 생성
  src/config.js
Labels: 완료

#12 [38기 강은지] ADD: 예약조회 페이지 추가
  src/Router.js
  src/pages/Book/Book.js
  src/pages/Book/BookedPlace.js
  src/pages/Book/Empty.js
  src/utils/utilFunc.js
Labels: 완료

#15 [38기 강은지] HOTFIX: routing 재설정, package.json 수정
  package-lock.json
  src/Router.js
  src/pages/Filter/FilterModal.js
  src/pages/Filter/ThemeFilter.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#8 [38기 정관훈]ADD: 메인페이지 전체지도 레이아웃
  public/data/markerData.json
  src.zip
  src/pages/Host/HostResult.js
  src/pages/Main/Main.js
  src/pages/Main/MainLayout.js
  src/pages/Map/MainMap.js
  src/pages/Map/MapBtn.js
  src/pages/Map/Mapcontext.js
  src/pages/Map/Marker.js
Labels: 완료

#10 [38기 강은지]ADD: gnb 컴포넌트 추가
  .eslintrc
  jsconfig.json
  package-lock.json
  package.json
  public/images/logo.png
  src/Router.js
  src/assets/icons/left-arrow.png
  src/assets/icons/right-arrow.png
  src/assets/maps/gyeonggi.png
  src/assets/maps/incheon.png
  src/assets/maps/seoul.png
  src/components/Footer/Footer.js
  src/components/Modal/SignInModal.js
  src/components/Nav/GlobalNav/GlobalNav.js
  src/components/Nav/GlobalNav/Search.js
  src/components/Nav/GlobalNav/SearchDetail.js
  src/components/Nav/GlobalNav/modals/Calendar.js
  src/components/Nav/GlobalNav/modals/Guest.js
  src/components/Nav/GlobalNav/modals/Location.js
  src/components/Nav/GlobalNav/modals/Profile.js
  src/components/Nav/GlobalNav/modals/UserProfile.js
  src/components/Nav/Nav.js
  src/components/SignIn/SignIn.js
  src/config.js
  src/pages/Book/Book.js
  src/pages/Book/BookedPlace.js
  src/pages/Book/Empty.js
  src/pages/Filter/FilterModal.js
  src/pages/Filter/ThemeFilter.js
  src/pages/Host/DragDrop/Dropzone.js
  src/pages/Host/Host.js
  src/pages/Host/HostStair/HostBed.js
  src/pages/Host/HostStair/HostHouse.js
  src/pages/Host/HostStair/HostInfo.js
  src/pages/Host/HostStair/HostMap.js
  src/pages/Host/HostStair/HostPicture.js
  src/pages/Host/HostStair/HostPrice.js
  src/pages/KakaoLogin/KakaoLogin.js
  src/pages/Main/List/ListMain.js
  src/pages/Main/Main.js
  src/pages/Map/MainMap.js
  src/pages/Map/MapBtn.js
  src/styles/theme.js
  src/utils/format/index.js
  src/utils/queryString/index.js
  src/utils/utilFunc.js
Labels: 멘토 리뷰 요청

#16 [38기 김우진]ADD: Skeleton 기능구현
  src/pages/Main/List/ListMain.js
  src/pages/Main/List/Skeleton.js
  src/pages/Main/MainText.js
Labels: 멘토 리뷰 요청

#17 [38기 김우진]ADD: useContext 사용한 기능구현
  src/Router.js
  src/context/ThemeContext.js
  src/pages/Filter/Filter.js
  src/pages/Filter/FilterModal.js
  src/pages/Filter/ThemeFilter.js
  src/pages/Main/AmenityFilterContext.js
  src/pages/Main/List/ListCard.js
  src/pages/Main/List/ListMain.js
Labels: 완료

#18 [38기 김도영] Feature/detail page
  src/components/Calander/CalanderComponent.js
  src/pages/Detail/Detail.js
  src/pages/Filter/Filter.js
  src/pages/Filter/FilterModal.js
  src/pages/KakaoLogin/KakaoLogin.js
Labels: 수정 요청
